
# This is a basic workflow to help you get started with Actions

name: Durchlauftest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt-get update
        sudo apt-get install lilypond
        cd Rohdaten/Noten
        lilypond Herbstlied_Noten.ly 
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: Rohdaten/Noten/Herbstlied_Noten.pdf
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Herbstlied_Liedblatt.tex
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: Herbstlied_Liedblatt.pdf
        

    - name: Create a Release
      uses: actions/create-release@v1
      with:
    # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: github.GITHUB_REF
    # The name of the release. For example, `Release v1.0.1`
        release_name: github.GITHUB_REF
        
  
